version: '3.9'
services:
  mongo:
    image: mongo:latest
    # contater_name: mongo
    env_file:
      - ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE} 
    volumes:
      - mongo:/data/db
      - ./database/mongo/data:/data/db
    ports:
      - '6000:27017'

volumes:
  mongo:
